package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u112/7884/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, September 22, 2016 9:04:05 PM PDT
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
   * The CDR Encapsulation encoding.
   * @see CodecFactory
   */
  public static final short value = (short)(0);
}
